# Generated by Django 4.2.7 on 2023-11-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='size',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
